name: MLflow CI Pipeline

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow==2.8.1 scikit-learn==1.3.0 pandas==2.0.3 numpy==1.24.3 matplotlib==3.7.2 seaborn==0.12.2
    
    - name: Run MLflow experiment
      run: |
        cd MLProject
        python modelling.py
    
    - name: Build Docker image
      run: |
        cd MLProject
        docker build -t weather-prediction-model:test .
    
    - name: Test Docker container
      run: |
        docker run --rm weather-prediction-model:test
